const { chromium } = require('playwright');
const expect = (condition, message) => { if (!condition) throw new Error(message); };
(async () => {
  const browser = await chromium.launch({headless:true,executablePath:'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'});
  const page = await browser.newPage({viewport:{width:390,height:844}}); page.setDefaultTimeout(5000);
  const pageErrors=[]; page.on('pageerror',error=>pageErrors.push(error.message));
  await page.goto('http://127.0.0.1:8877/?v=v47',{waitUntil:'networkidle'});
  expect(await page.locator('[data-v47search]').isVisible(),'Ver 4.7 search input should be visible');
  expect(await page.getByText('실시간 검색어 순위',{exact:true}).isVisible(),'real-time search ranking heading should appear below search');
  expect(await page.locator('[data-v47trend]').count()===4,'real-time search ranking should expose four keyword chips');
  expect(await page.getByText('자주 묻는 질문',{exact:true}).isVisible(),'popular inquiry heading should be visible');
  expect(await page.getByText('최근 이용 메뉴',{exact:true}).isVisible(),'recent menu section should be visible');
  expect(await page.getByText('전체 메뉴',{exact:true}).isVisible(),'all menu heading should be visible');
  expect(await page.locator('[data-v47search]').getAttribute('placeholder')==='무엇을 도와드릴까요?','search placeholder should use the requested copy');
  expect(await page.locator('.v47-hero__title').count()===0,'main page title should be hidden');
  expect(await page.locator('[data-v47recent] small').count()===0,'recent menus should show names without descriptions');
  const sectionOrder=await page.locator('[data-v47search], [data-v47trends], .v45-selfsolve, [data-v47recent-section]').evaluateAll(els=>els.map(el=>el.getBoundingClientRect().top));
  expect(sectionOrder.length===4 && sectionOrder.every((top,index)=>index===0||top>=sectionOrder[index-1]),'home sections should be ordered search, trends, popular inquiries, recent menus');
  const trendKeyword=await page.locator('[data-v47trend]').first().getAttribute('data-v47trend');
  await page.locator('[data-v47trend]').first().click();
  expect(await page.locator('[data-v47search]').inputValue()===trendKeyword,'clicking a ranked keyword should populate search');
  expect(await page.locator('[data-v47searchresults]').isVisible(),'clicking a ranked keyword should open recommended solutions');
  await page.locator('[data-v47search]').fill('');
  await page.locator('[data-v47search]').fill('비밀번호'); await page.locator('[data-v47search]').press('Enter');
  expect(await page.locator('[data-v47searchresult]').count()>=4,'password search should offer multiple routes');
  for(const label of ['직접 처리','앱에서 처리','안내 확인','상담 연결']) expect(await page.getByText(label,{exact:true}).count()>0,`missing route badge: ${label}`);
  await page.locator('[data-v47search]').fill('');
  expect(!(await page.locator('[data-v47searchresults]').isVisible()),'clearing the query should hide recommended solutions');
  await page.locator('[data-v47search]').fill('비밀번호'); await page.locator('[data-v47search]').press('Enter');
  await page.locator('.v47-grid').click({position:{x:5,y:5}});
  expect(!(await page.locator('[data-v47searchresults]').isVisible()),'clicking outside search recommendations should hide them');
  await page.locator('[data-v47search]').fill('비밀번호'); await page.locator('[data-v47search]').press('Enter');
  await page.getByText('ID 비밀번호 재설정',{exact:true}).click();
  expect(await page.locator('#v47MiName').isVisible(),'ID result should open the Ver 4.7 my-info flow');
  expect(await page.locator('.v47mi-stepper[aria-label*="ID 조회·비밀번호 초기화"]').count()>0,'ID result should use the Ver 4.7 stepper');
  await page.locator('[data-s1back]').first().click();
  expect(await page.locator('[data-v47search]').isVisible(),'back should return to search home');
  expect((await page.locator('[data-v47recent]').first().innerText()).includes('ID 비밀번호 재설정'),'completed navigation should move the used menu to the front of recent menus');
  await page.locator('[data-v47search]').fill('비밀번호'); await page.locator('[data-v47search]').press('Enter');
  await page.getByText('계좌 비밀번호 변경',{exact:true}).click();
  expect(await page.getByText('계좌비밀번호를 안내해 드릴게요',{exact:true}).isVisible(),'account password should open the Ver 4.7 guide');
  expect(await page.locator('.v47mi-stepper').count()>0,'account password guide should use the Ver 4.7 stepper');
  await page.locator('[data-s1back]').first().click();
  await page.locator('[data-v47search]').fill('공동인증서'); await page.locator('[data-v47search]').press('Enter');
  await page.getByText('공동인증서 비밀번호 안내',{exact:true}).click();
  expect(await page.getByText('기타서비스',{exact:true}).isVisible(),'certificate result should open the Ver 4.7 category page');
  expect(await page.locator('[data-v47sub="간편인증·공동인증서"]').count()>0,'certificate result should expose the Ver 4.7 submenu');
  await page.locator('[data-s1back]').first().click();
  await page.locator('[data-v47search]').fill('서류'); await page.locator('[data-v47search]').press('Enter');
  await page.getByText('서류 신청·발급',{exact:true}).click();
  expect(await page.getByText('어떤 서류가 필요하세요?',{exact:true}).isVisible(),'document result should open the Ver 4.7 untact flow');
  await page.locator('[data-s1back]').first().click();
  await page.locator('[data-v47search]').fill('전혀없는검색어'); await page.locator('[data-v47search]').press('Enter');
  expect(await page.getByText('검색 결과를 찾지 못했어요',{exact:false}).count()>0,'empty result guidance should be visible');
  expect(await page.getByText('전체 메뉴에서 찾기',{exact:false}).count()>0,'empty result should suggest full menu');
  await page.locator('[data-sian="s1"][data-ver="v46"]').evaluate(el=>el.click());
  expect(await page.locator('[data-v47search]').count()===0,'search should not appear in Ver 4.6');
  expect(pageErrors.length===0,`page errors: ${pageErrors.join(' | ')}`);
  await browser.close(); console.log('v47 search tests passed');
})().catch(error=>{console.error(error);process.exit(1);});
